### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by dxvid-pts** [peterscodee/audio_cast#1]
### This issue is important for everyone interested in contributing

The plugin will support `Chromecast` via [dart_chromecast](https://pub.dev/packages/dart_chromecast), `Airplay` via [multicast_dns](https://pub.dev/packages/multicast_dns), and `DLNA` via [upnp](https://pub.dev/packages/upnp). I am currently working on getting `Chromecast` support ready while `DLNA` is already implemented and working.

Similar to the [federated plugin architecture](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit) everyone interested in contributing can write his own [`CastAdapter`](https://github.com/peterscodee/audio_cast/blob/master/lib/src/adapter/adapter.dart#LC15:~:text=CastAdapter,-%7B).

If you are, comment on this thread and we can find a task for you to do.

### Tasks that can be done:
- [ ] Add documentation
- [x] Migrate [mp3_info](https://pub.dev/packages/mp3_info) to nullsafety (simple!)
- [x] Migrate [upnp](https://pub.dev/packages/upnp) to nullsafety
- [x]  Migrate [dart_chromecast](https://pub.dev/packages/dart_chromecast) to nullsafety
- [ ]  Add support for `Airplay` (through `AirplayCastAdapter`)
- [ ]  ~~Add `Chromecast` support~~ @peterscodee

**Comment by bafplus** [comment]
This is exactly what i need. Care to share details and status?

**Comment by daniel-naegele** [comment]
It seems like, that the `mp3_info` as well as the `dart_chromecast` packages are null safe now. 
I would like to help/contribute to this package as good as possible. Do you still want to develop/maintain this plugin? What is the current status of `Airplay` support? Do you need help implementing it?

**Comment by dxvid-pts** [comment]
I am willing to maintain this plugin and review pull requests. I don't actively add features for now as I currently don't need them but if someone is putting work into the project I will respond quickly.

Yes, migrating this to null safety would be a good start.
